# This workflow will upload a Python Package to PyPI when a release is created
name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/django-hurricane
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Install project
      run: poetry install --no-interaction
    - name: Check code climate
      run: |
        poetry build
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
